name: Cypress automation

on: push

jobs:
  chrome-headless:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Headless Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome